//
// Created by Anne on 6-6-2018.
//

#ifndef RHYTHMIC_PROGRAMMING_GAME_INPUTTYPES_H
#define RHYTHMIC_PROGRAMMING_GAME_INPUTTYPES_H

enum BeatType {
    TAPBEAT,
    HOLDBEAT
};

#endif //RHYTHMIC_PROGRAMMING_GAME_INPUTTYPES_H
