//
// Created by patri on 5/25/2018.
//

#ifndef RHYTHMIC_PROGRAMMING_GAME_INTERPOLATION_TYPE_H
#define RHYTHMIC_PROGRAMMING_GAME_INTERPOLATION_TYPE_H

enum InterpolationType {
    LINEAR,
    QUAD
};

#endif //RHYTHMIC_PROGRAMMING_GAME_INTERPOLATION_TYPE_H
